# Generated by Django 4.2.24 on 2025-10-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtask",
            name="solution_file",
            field=models.FileField(blank=True, null=True, upload_to="solutions/"),
        ),
    ]
